In [1]:
from numpy import *

In [2]:
random.rand(4, 4)

array([[ 0.30920536,  0.7560181 ,  0.65894068,  0.8775558 ],
       [ 0.91969471,  0.95959826,  0.75044493,  0.77197728],
       [ 0.82323493,  0.44332857,  0.69791546,  0.85870513],
       [ 0.32627377,  0.45222041,  0.43738437,  0.13712411]])

In [4]:
randMat = mat(random.rand(4, 4))
#inverse matrix
randMat.I

matrix([[ 1.32950126, -1.83159209,  0.70919862, -0.14274971],
        [-2.42126709,  1.32703788, -1.27631765,  3.34973195],
        [-1.78891944,  0.49680342,  1.26914131,  0.32066021],
        [ 2.1763624 ,  0.47020756,  0.07436638, -2.52932349]])

In [5]:
invRandMat = randMat.I
randMat * invRandMat

matrix([[  1.00000000e+00,   3.88578059e-16,  -4.16333634e-17,
           4.44089210e-16],
        [  0.00000000e+00,   1.00000000e+00,  -1.38777878e-16,
           4.44089210e-16],
        [  0.00000000e+00,   5.55111512e-17,   1.00000000e+00,
           0.00000000e+00],
        [ -2.22044605e-16,   3.88578059e-16,  -2.08166817e-16,
           1.00000000e+00]])

In [6]:
eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])